version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: ./php
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  apache-exporter:
    image: bitnami/apache-exporter:latest
    ports:
      - 9117:9117
    command:
      - --scrape_uri=http://localhost:8000/server-status/?auto
  db:
    container_name: db
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - '8082:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
