global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'apache-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['f1ade9b0536b:9117']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
