name: Build and push to DockerHub

on:
  push:
    branches: [ master, main ]
    
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: test
        run: |      
          pwd
          
      - name: Docker build App-php
        run: |      
          docker build ./php -t mkjoseva/devops-php
          
      - name: Docker build MySQL
        run: | 
          docker build ./db -t mkjoseva/devops-msql
          
      - name: Docker build PHPMyAdmin
        run: |      
          docker build ./phpmyadmin -t mkjoseva/devops-phpmyadmin
          
      - name: Docker push App-php
        run: |      
          docker push mkjoseva/devops-php
          
      - name: Docker push MySQL
        run: | 
          docker push mkjoseva/devops-msql
          
      - name: Docker push PHPMyAdmin
        run: |      
          docker push mkjoseva/devops-phpmyadmin
      
